"""Schemas package — re-exports all API models from api.py."""

from backend.schemas.api import (
    BaseResponse,
    ErrorResponse,
    HealthResponse,
    MetricsResponse,
    BoundingBox,
    Detection,
    ImagePredictRequest,
    ImagePredictResponse,
    VideoPredictRequest,
    VideoPredictResponse,
    CameraFrameRequest,
    CameraFrameResponse,
    SentenceState,
    SentenceResetResponse,
    SentenceExportResponse,
    HistoryEntry,
    HistoryResponse,
    HistoryDeleteResponse,
    SettingsResponse,
    SettingsUpdateRequest,
    SettingsUpdateResponse,
    UploadResponse,
)

__all__ = [
    "BaseResponse",
    "ErrorResponse",
    "HealthResponse",
    "MetricsResponse",
    "BoundingBox",
    "Detection",
    "ImagePredictRequest",
    "ImagePredictResponse",
    "VideoPredictRequest",
    "VideoPredictResponse",
    "CameraFrameRequest",
    "CameraFrameResponse",
    "SentenceState",
    "SentenceResetResponse",
    "SentenceExportResponse",
    "HistoryEntry",
    "HistoryResponse",
    "HistoryDeleteResponse",
    "SettingsResponse",
    "SettingsUpdateRequest",
    "SettingsUpdateResponse",
    "UploadResponse",
]
